"""Reconstruction DeepJSCC training (smoke scale for Step 4).

Training protocol frozen by the project specification:

* objective: the frozen reconstruction loss on the NORMALIZED state
  (losses.reconstruction_loss); no task terms, no controller/dynamics in
  the graph.
* training states: the frozen protocol of audit A9 - states generated by
  rolling out the noiseless full-information PD controller. The initial
  states come from the same frozen sampler as evaluation (v0 = 0, d_min
  enforced); the network therefore sees the same normalized state
  representation the task-oriented model will use later.
* training SNR: Uniform(SNR_TRAIN_RANGE_DB) = U(0, 20) dB (audit 2.4).
  The vectorized channel contract takes one SNR per batch, so the smoke
  trainer draws one SNR per batch; the audit's per-sample law (A8) is the
  full-training refinement.
* optimizer: Adam(lr = LEARNING_RATE), gradient clipping global-norm 1.0
  (audit 2.6). Seeds via config.set_global_seed + purpose generators.

This entry point runs a SMOKE budget (proof of learning, not the final
experiment): modest steps, fixed seed, fully deterministic.
"""

from __future__ import annotations

import math
from typing import Optional, Tuple

import torch

from project import config
from project.data.normalization import normalize
from project.losses.reconstruction_loss import reconstruction_loss
from project.models.reconstruction_jscc import ReconstructionDeepJSCC
from project.uav.environment import NavigationEnv


def _group_grad_norm(params) -> float:
    total = 0.0
    for p in params:
        if p.grad is not None:
            total += float(p.grad.norm()) ** 2
    return math.sqrt(total)


def train_reconstruction(
    k: int = 3,
    channel: str = "awgn",
    seed: int = 42,
    steps: int = 400,
    batch_states: int = 2048,
    lr: Optional[float] = None,
    snr_range: Tuple[float, float] = config.SNR_TRAIN_RANGE_DB,
    verbose_every: int = 0,
) -> Tuple[ReconstructionDeepJSCC, dict]:
    """Train the reconstruction baseline; return (model, report).

    The default budget is the SMOKE scale required by Step 4 (proof of
    finite, reproducible, meaningful learning) - not the final protocol.
    """
    config.set_global_seed(seed)          # weight init
    gen_states = config.derive_generator("episodes", seed)
    gen_snr = config.derive_generator("noise_train", seed)
    gen_noise = config.derive_generator("noise_test", seed)
    env = NavigationEnv()

    lr = config.LEARNING_RATE if lr is None else lr
    model = ReconstructionDeepJSCC(k=k)
    opt = torch.optim.Adam(model.parameters(), lr=lr)
    enc_params = list(model.encoder.parameters())
    dec_params = list(model.decoder.parameters())

    history = []
    grad_enc_hist = []
    grad_dec_hist = []
    nan_batches = 0
    loss_initial = None

    for step_idx in range(steps):
        # --- frozen state protocol (A9): starts + v0=0 + goal -> [B, 6]
        p0, v0, goal = env.sample_starts(batch_states, generator=gen_states)
        s = torch.cat([p0, v0, goal], dim=-1)

        # --- U(0, 20) dB per batch (see module docstring for granularity)
        snr_db = float(torch.empty(1).uniform_(
            snr_range[0], snr_range[1], generator=gen_snr))

        s_bar_hat = model.forward_losses(s, snr_db, channel=channel,
                                         generator=gen_noise)
        target = normalize(s)             # clean normalized ground truth

        loss = reconstruction_loss(s_bar_hat, target)

        if not bool(torch.isfinite(loss)):
            nan_batches += 1
            opt.zero_grad(set_to_none=True)
            continue

        opt.zero_grad(set_to_none=True)
        loss.backward()
        g_enc = _group_grad_norm(enc_params)
        g_dec = _group_grad_norm(dec_params)
        torch.nn.utils.clip_grad_norm_(model.parameters(),
                                       max_norm=config.GRAD_CLIP_NORM)
        opt.step()

        loss_val = float(loss)
        history.append(loss_val)
        grad_enc_hist.append(g_enc)
        grad_dec_hist.append(g_dec)
        if loss_initial is None:
            loss_initial = loss_val
        if verbose_every and (step_idx % verbose_every == 0 or
                              step_idx == steps - 1):
            print(f"  [{channel} k={k}] step {step_idx:4d}  "
                  f"snr {snr_db:5.1f} dB  loss {loss_val:.5f}  "
                  f"|g_enc| {g_enc:.3f}  |g_dec| {g_dec:.3f}")

    report = {
        "channel": channel,
        "k": k,
        "seed": seed,
        "steps": steps,
        "batch_states": batch_states,
        "lr": lr,
        "snr_range_db": snr_range,
        "loss_initial": loss_initial,
        "loss_final": history[-1] if history else float("nan"),
        "loss_reduction_pct": (100.0 * (1.0 - history[-1] / loss_initial)
                               if history and loss_initial else float("nan")),
        "grad_norm_encoder_initial": grad_enc_hist[0] if grad_enc_hist else float("nan"),
        "grad_norm_encoder_final": grad_enc_hist[-1] if grad_enc_hist else float("nan"),
        "grad_norm_decoder_initial": grad_dec_hist[0] if grad_dec_hist else float("nan"),
        "grad_norm_decoder_final": grad_dec_hist[-1] if grad_dec_hist else float("nan"),
        "nan_batches": nan_batches,
        "history": history,
        "grad_encoder_history": grad_enc_hist,
        "grad_decoder_history": grad_dec_hist,
        "n_params": sum(p.numel() for p in model.parameters()),
    }
    return model, report


if __name__ == "__main__":
    for ch in ("awgn", "rayleigh"):
        _, rep = train_reconstruction(channel=ch, verbose_every=100)
        print(f"\n=== {ch.upper()} smoke train ===")
        for key, val in rep.items():
            if key not in ("history", "grad_encoder_history",
                           "grad_decoder_history"):
                print(f"  {key}: {val}")
